import type { Metadata } from "next";
import { Container } from "@/components/layout/container";
import { MotionSection } from "@/components/layout/motion-section";
import { SectionHeading } from "@/components/layout/section-heading";

export const metadata: Metadata = { title: "About", description: "Learn about Atelier Graded, a private showroom for graded collectibles.", openGraph: { title: "About Atelier Graded" } };
export default function AboutPage() {
  return <><Container className="py-16 sm:py-28"><SectionHeading eyebrow="The atelier" title="A quieter place to collect." description="Atelier Graded is a private showroom for graded collectibles, built around clarity, thoughtful presentation, and personal attention." /><div className="mt-14 grid gap-10 border-t border-border pt-10 lg:grid-cols-2"><p className="font-display text-4xl leading-tight">We believe a meaningful collection is shaped by the stories and standards behind each object—not only the numbers on a label.</p><div className="space-y-6 text-sm leading-8 text-muted-foreground"><p>Our listings bring together condition details, grading information, photography, and provenance notes so collectors can make their own informed decisions. We are an independent marketplace and do not represent any card publisher, grader, or intellectual property owner.</p><p>All inventory shown in this development showroom is fictional demonstration inventory and is not an offer for an authentic collectible. Any recognizable character names are used solely to describe the fictional catalog records.</p></div></div></Container><MotionSection className="border-y border-border bg-card/30 py-16 sm:py-24"><Container><SectionHeading eyebrow="Our approach" title="Present less. Present it better." /><div className="mt-12 grid gap-8 md:grid-cols-3">{[["The edit","A focused collection rather than an endless feed."],["The record","Details designed to support independent verification."],["The conversation","Inquiry-led service for questions, offers, and shipping."]].map(([title, copy]) => <div key={title} className="border-t border-gold/50 pt-5"><h2 className="font-display text-3xl">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{copy}</p></div>)}</div></Container></MotionSection></>;
}
