import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { CatalogGrid } from "@/components/cards/catalog-grid";
import { InquiryForm } from "@/components/inquiry/inquiry-form";
import { Container } from "@/components/layout/container";
import { MotionSection } from "@/components/layout/motion-section";
import { SectionHeading } from "@/components/layout/section-heading";
import { getCardBySlug, getCards } from "@/lib/data/repository";

const money = (amount: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount / 100);
type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const card = await getCardBySlug((await params).slug);
  if (!card || card.publicationStatus !== "PUBLISHED") return { title: "Card not found" };
  return { title: card.title.replace(/^DEMO Inventory — /, ""), description: `${card.grader} ${card.grade} · ${card.setName ?? "Graded collectible"} · ${money(card.priceMinor, card.currency)}`, openGraph: { title: `${card.title.replace(/^DEMO Inventory — /, "")} | Atelier Graded`, description: card.description ?? undefined, images: card.images[0] ? [card.images[0].imageUrl] : [] } };
}

export default async function CardDetailPage({ params }: Props) {
  const card = await getCardBySlug((await params).slug);
  if (!card || card.publicationStatus !== "PUBLISHED") notFound();
  const related = (await getCards({ availability: ["AVAILABLE"], perPage: 12 })).items.filter((item) => item.id !== card.id && (item.setName === card.setName || item.grader === card.grader)).slice(0, 3);
  const specs: Array<[string, string | number | null | boolean]> = [["Title", card.title.replace(/^DEMO Inventory — /, "")], ["Category", card.category], ["Year", card.year], ["Set", card.setName], ["Set code", card.setCode], ["Card number", card.cardNumber], ["Set total", card.setTotal], ["Rarity", card.rarity], ["Variant", card.variant], ["Edition", card.edition], ["Finish", card.finish], ["Language", card.language], ["Grader", card.grader], ["Grade", card.grade], ["Grade label", card.gradeLabel], ["Certificate number", card.certificationNumber], ["Price", money(card.priceMinor, card.currency)], ["Negotiable", card.priceNegotiable ? "By inquiry" : "No"], ["Availability", card.availabilityStatus], ["Population", card.populationCount], ["Shipping regions", card.shippingRegions], ["Acquired", card.acquiredAt ? new Date(card.acquiredAt).toLocaleDateString() : null], ["Listed", card.listedAt ? new Date(card.listedAt).toLocaleDateString() : null], ["Sold", card.soldAt ? new Date(card.soldAt).toLocaleDateString() : null]];
  const product = card.availabilityStatus === "AVAILABLE" ? { "@context": "https://schema.org", "@type": "Product", name: card.title.replace(/^DEMO Inventory — /, ""), description: card.description, image: card.images.map((image) => image.imageUrl), sku: card.certificationNumber, offers: { "@type": "Offer", priceCurrency: card.currency, price: card.priceMinor / 100, availability: "https://schema.org/InStock", url: `/cards/${card.slug}` } } : null;
  const breadcrumbs = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "/" }, { "@type": "ListItem", position: 2, name: "Collection", item: "/cards" }, { "@type": "ListItem", position: 3, name: card.title.replace(/^DEMO Inventory — /, "") }] };
  const structuredData = JSON.stringify([breadcrumbs, ...(product ? [product] : [])]).replace(/</g, "\\u003c");
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: structuredData }} /><Container className="py-10 sm:py-16"><nav className="mb-8 text-xs font-bold uppercase tracking-[.16em] text-muted-foreground"><Link href="/cards" className="hover:text-gold">Collection</Link> <span className="mx-2">/</span> {card.pokemonName}</nav><div className="grid gap-12 lg:grid-cols-[minmax(0,1.1fr)_minmax(340px,.9fr)]"><div className="grid gap-4 sm:grid-cols-2">{card.images.map((image) => <div key={image.id} className="slab-glare relative aspect-[4/5] bg-card"><Image src={image.imageUrl} alt={image.altText ?? card.title} fill priority={image.sortOrder === 0} className="object-cover p-5" /></div>)}</div><div><p className="text-xs font-bold uppercase tracking-[.22em] text-gold">{card.grader} · {card.gradeLabel ?? card.grade}</p><h1 className="mt-4 font-display text-5xl leading-[.9] sm:text-6xl">{card.title.replace(/^DEMO Inventory — /, "")}</h1><p className="mt-5 text-sm leading-7 text-muted-foreground">{card.description}</p><div className="mt-8 border-y border-border py-6"><p className="font-display text-4xl text-gold">{card.availabilityStatus === "SOLD" ? "Sold" : money(card.priceMinor, card.currency)}</p><p className="mt-2 text-xs text-muted-foreground">{card.priceNegotiable ? "Private offers welcomed" : "Price presented for inquiry"}</p></div><div className="mt-8 border border-border bg-card p-6"><h2 className="font-display text-3xl">Private inquiry</h2><div className="mt-5"><InquiryForm cardId={card.id} /></div></div></div></div></Container>
    <MotionSection className="border-y border-border bg-card/30 py-16 sm:py-24"><Container><SectionHeading eyebrow="The record" title="Object details" /><dl className="mt-10 grid border-l border-t border-border sm:grid-cols-2">{specs.filter(([, value]) => value !== null && value !== "").map(([label, value]) => <div key={label} className="border-b border-r border-border px-4 py-4"><dt className="text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">{label}</dt><dd className="mt-1 text-sm">{String(value)}</dd></div>)}</dl></Container></MotionSection>
    <MotionSection className="py-16 sm:py-24"><Container><div className="grid gap-10 lg:grid-cols-2"><div><SectionHeading eyebrow="Grader record" title={`${card.grader} metadata`} /><dl className="mt-8 grid gap-px border border-border bg-border sm:grid-cols-2">{Object.entries(card.graderMetadata).filter(([, value]) => value !== null && value !== undefined && value !== "").map(([key, value]) => <div key={key} className="bg-background p-4"><dt className="text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="mt-1 text-sm">{String(value)}</dd></div>)}</dl></div><div className="border border-gold/25 p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Independent verification</p><h2 className="mt-3 font-display text-4xl">Do your own due diligence.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Grader links and certificate details are provided as a research aid. Buyers should independently verify every item before acquiring it; a verification record does not eliminate counterfeit, alteration, or condition risk.</p>{card.verificationUrl && <a className="mt-6 inline-block border border-gold/50 px-5 py-3 text-sm font-semibold text-gold hover:bg-gold/10" href={card.verificationUrl} target="_blank" rel="noreferrer">Visit grader verification →</a>}</div></div></Container></MotionSection>
    {related.length > 0 && <MotionSection className="border-t border-border py-16 sm:py-24"><Container><SectionHeading eyebrow="Continue exploring" title="Related cards" /><div className="mt-10"><CatalogGrid cards={related} /></div></Container></MotionSection>}</>;
}
